[package]
name = "noah-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
prost = "0.12"
bytes = "1.5"
thiserror = "1.0"
tonic = "0.10"

[build-dependencies]
tonic-build = { workspace = true }
